-- Catálogo de Condiciones Crónicas / Permanentes
USE `servicio_medico`;

INSERT IGNORE INTO `lista_condiciones` (`condicion`) VALUES
('Asma Bronquial'),
('Diabetes mellitus Tipo 1'),
('Diabetes mellitus Tipo 2'),
('Hipertensión Arterial'),
('Alergia a la Penicilina'),
('Alergia a las Sulfas'),
('Alergia a la Aspirina'),
('Hipotiroidismo'),
('Hipertiroidismo'),
('Artritis Reumatoide'),
('Insuficiencia Renal Crónica'),
('Insuficiencia Cardíaca'),
('Enfermedad Pulmonar Obstructiva Crónica (EPOC)'),
('Cardiopatía Isquémica'),
('Epilepsia'),
('Migraña Crónica'),
('Enfermedad de Parkinson'),
('Alzheimer / Demencia'),
('Depresión Mayor'),
('Ansiedad Generalizada'),
('Artrosis / Osteoartritis'),
('Lupus Eritematoso Sistémico'),
('Fibromialgia'),
('Cirrosis Hepática'),
('Obesidad Mórbida'),
('Celiaquía / Alergia al Gluten'),
('Dislipidemia (Colesterol/Triglicéridos Altos)'),
('Hiperplasia Prostática Benigna'),
('Anemia Falciforme'),
('Psoriasis Crónica');
