-- Catálogo de Condiciones Crónicas / Permanentes
USE `servicio_medico`;

INSERT IGNORE INTO `lista_condiciones` (`condicion`) VALUES
('Asma Bronquial'),
('Asma Alérgica'),
('Asma Ocupacional'),
('Diabetes mellitus Tipo 1'),
('Diabetes mellitus Tipo 2'),
('Hipertensión Arterial'),
('Alergia a la Penicilina'),
('Alergia a las Sulfas'),
('Alergia a la Aspirina (AINEs)'),
('Alergia al Látex'),
('Alergia a la Lidocaína'),
('Alergia a los Mariscos'),
('Alergia al Huevo'),
('Celiaquía / Alergia al Gluten'),
('Intolerancia a la Lactosa'),
('Hipotiroidismo'),
('Hipertiroidismo'),
('Artritis Reumatoide'),
('Artritis Psoriásica'),
('Insuficiencia Renal Crónica'),
('Insuficiencia Cardíaca'),
('Arritmia Cardíaca Crónica'),
('Cardiopatía Isquémica'),
('Secuelas de Accidente Cerebrovascular (ACV)'),
('Enfermedad Pulmonar Obstructiva Crónica (EPOC)'),
('Epilepsia'),
('Migraña Crónica'),
('Enfermedad de Parkinson'),
('Alzheimer / Demencia'),
('Esclerosis Múltiple'),
('Depresión Mayor'),
('Ansiedad Generalizada'),
('Trastorno Bipolar'),
('Esquizofrenia'),
('Trastorno por Déficit de Atención con Hiperactividad (TDAH)'),
('Trastorno Obsesivo Compulsivo (TOC)'),
('Artrosis / Osteoartritis'),
('Lupus Eritematoso Sistémico'),
('Fibromialgia'),
('Cirrosis Hepática'),
('Obesidad Mórbida'),
('Dislipidemia (Colesterol/Triglicéridos Altos)'),
('Hiperplasia Prostática Benigna'),
('Anemia Falciforme'),
('Psoriasis Crónica'),
('Cáncer de Mama (en control/remisión)'),
('Cáncer de Próstata (en control/remisión)'),
('Trombofilia'),
('Hemofilia'),
('Síndrome Metabólico');
